config:
  # Root of the installation tree
  install_tree: /ssoft/spack/paien/v3/opt/spack/

  # Root of the module files
  module_roots:
    tcl: /ssoft/spack/paien/v3/share/spack/modules
    lmod: /ssoft/spack/paien/v3/share/spack/lmod
    dotkit: /ssoft/spack/paien/v3/share/spack/dotkit

  build_stage:
    - /tmp/paien.v3
