config:
  # Root of the installation tree
  install_tree: /ssoft/spack/humagne/v1/opt/spack/

  # Root of the module files
  module_roots:
    tcl: /ssoft/spack/humagne/v1/share/spack/modules
    lmod: /ssoft/spack/humagne/v1/share/spack/lmod
    dotkit: /ssoft/spack/humagne/v1/share/spack/dotkit

  build_stage:
    - /tmp/humagne.v1